CMSys/CMSys.Web/Areas/Admin/ViewModels/TrainerGroupViewModel.cs
using System.Collections.Generic;
using CMSys.Core.Entities;

namespace CMSys.Web.Areas.Admin.ViewModels
{
    public class TrainerGroupViewModel
    {
        public TrainerGroup TrainerGroup { get; set; }
        public IEnumerable<TrainerGroup> Groups { get; set; }
    }
}

CMSys/CMSys.Web/Areas/Admin/Controllers/TrainerGroupController.cs
using System;
using CMSys.Core.Entities;
using CMSys.Core.Repositories;
using CMSys.Web.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Route("admin/[controller]")]
    public class TrainerGroupController : Controller
    {
        private readonly IUnitOfWork _uow;

        public TrainerGroupController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        [Route("")]
        [Route("[area]/[controller]/[action]")]
        public IActionResult List()
        {
            return View(new TrainerGroupViewModel
            {
                Groups = _uow.TrainerGroupRepository.List(),
                TrainerGroup = new TrainerGroup()
            });
        }

        [HttpPost("[action]")]
        public IActionResult Edit(TrainerGroupViewModel model)
        {
            var group = _uow.TrainerGroupRepository.Find(model.TrainerGroup.Id);
            if (group == null) return NotFound();

            group.Name = model.TrainerGroup.Name;
            group.Description = model.TrainerGroup.Description;
            group.VisualOrder = model.TrainerGroup.VisualOrder;

            _uow.Commit();
            return RedirectToAction("List");
        }

        [HttpPost("[action]/{id:guid}")]
        public IActionResult Delete(Guid id)
        {
            var group = _uow.TrainerGroupRepository.Find(id);
            if (group == null)
                return NotFound();
            if (group.Trainer == null)
            {
                _uow.TrainerGroupRepository.Remove(group);
                _uow.Commit();
            }

            return RedirectToAction("List");
        }

        [HttpPost("[action]")]
        public IActionResult Add(TrainerGroupViewModel model)
        {
            var group = new TrainerGroup();

            group.Id = Guid.NewGuid();
            group.Name = model.TrainerGroup.Name;
            group.Description = model.TrainerGroup.Description;
            group.VisualOrder = model.TrainerGroup.VisualOrder;

            _uow.TrainerGroupRepository.Add(group);
            _uow.Commit();
            return RedirectToAction("List");
        }
    }
}

CMSys/CMSys.Web/Areas/Admin/Views/TrainerGroup/List.cshtml
@model CMSys.Web.Areas.Admin.ViewModels.TrainerGroupViewModel
@{
    ViewBag.Title = "Trainer groups";
}

<div>
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="text-primary headerdiv" style="text-transform: uppercase; font-weight: bold"></div>
                    <button class="close crossbutton" data-dismiss="modal" area-hidden="true">X</button>
                </div>
                <div class="modal-body">
                    <form class="formpopup" asp-area="Admin" asp-controller="TrainerGroup">
                        <div class="form-group">
                            <input asp-for="TrainerGroup.Id" class="form-control-plaintext idlabel" type="hidden" readonly="readonly" />
                        </div>
                        <div class="form-group" style="margin-top: -15px">
                            <label asp-for="TrainerGroup.Name">Name</label>
                            <input asp-for="TrainerGroup.Name" class="form-control namelabel" />
                            <span asp-validation-for="TrainerGroup.Name" class="text-danger namespan"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TrainerGroup.Description">Description</label>
                            <textarea asp-for="TrainerGroup.Description" class="form-control owerflow-auto descriptionlabel" placeholder="Put description here" rows="5" style="height: 60px"></textarea>
                        </div>
                        <div class="form-group">
                            <label asp-for="TrainerGroup.VisualOrder">Order</label>
                            <input asp-for="TrainerGroup.VisualOrder" class="form-control orderlabel" />
                            <span asp-validation-for="TrainerGroup.VisualOrder" class="text-danger orderspan"></span>
                        </div>
                        <div>
                            <input type="submit" class="btn btn-primary submitinput" />
                            <a class="btn btn-outline-secondary" data-dismiss="modal">Close</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<partial name="DeletePopUp" />

<div style="display: flex;float: right; margin-top: -10px">
    <a onclick="onAddTrainerGroupClick(event)" class="btn btn-outline-light" style="margin-bottom: 10px; border: 1px solid lightgray; width: 37px; height: 37px; display: block; background: whitesmoke ">
        <i onclick="onAddTrainerGroupClick(event)" class="fa fa-plus" aria-hidden="true" style="font-size:25px; display: block; margin-left: -47%; color: gray"></i>
    </a>
</div>

<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Order</th>
            <th scope="col" style="width: 100px">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model.Groups)
        {
            <tr>
                <th>@group.Name</th>
                <td>@group.Description</td>
                <td>@group.VisualOrder</td>
                <td>
                    <a onclick="onEditTrainerGroupClick(event)" id="@group.Id" class="btn btn-outline-light" style="border: 1px solid #007bff; margin-left: 5px; width: 30px;">
                        <i class="fas" id="@group.Id" style="font-size: 20px; display: block; margin-left: -185%; color: #007bff;"> &#xf303; </i>
                    </a>
                    <a onclick="onDeleteTrainerGroupClick(event)" id="@group.Id" class="btn btn-outline-light" style="border: 1px solid red; margin-left: 5px; width: 30px;">
                        <i id="@group.Id" style="font-size: 20px; display: block; margin-left: -172%; color: red;" class="fa fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}