CMSys/CMSys.Web/Areas/Admin/ViewModels/CourseGroupViewModel.cs
using System.Collections.Generic;
using CMSys.Core.Entities;

namespace CMSys.Web.Areas.Admin.ViewModels
{
    public class CourseGroupViewModel
    {
        public CourseGroup CourseGroup { get; set; }
        public IEnumerable<CourseGroup> Groups { get; set; }
    }
}

CMSys/CMSys.Web/Areas/Admin/Controllers/CourseGroupController.cs
using System;
using CMSys.Core.Entities;
using CMSys.Core.Repositories;
using CMSys.Web.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Route("admin/[controller]")]
    public class CourseGroupController : Controller
    {
        private readonly IUnitOfWork _uow;

        public CourseGroupController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        [Route("")]
        [Route("[action]")]
        public IActionResult List()
        {
            return View(new CourseGroupViewModel
            {
                Groups = _uow.CourseGroupRepository.List(),
                CourseGroup = new CourseGroup()
            });
        }

        [HttpPost("[action]")]
        public IActionResult Edit(CourseGroupViewModel model)
        {
            var group = _uow.CourseGroupRepository.Find(model.CourseGroup.Id);
            if (group == null) return NotFound();

            group.Name = model.CourseGroup.Name;
            group.Description = model.CourseGroup.Description;
            group.VisualOrder = model.CourseGroup.VisualOrder;

            _uow.Commit();
            return RedirectToAction("List");
        }

        [HttpPost("[action]/{id:guid}")]
        public IActionResult Delete(Guid id)
        {
            var group = _uow.CourseGroupRepository.Find(id);
            if (group == null)
                return NotFound();
            if (group.Course == null)
            {
                _uow.CourseGroupRepository.Remove(group);
                _uow.Commit();
            }

            return RedirectToAction("List");
        }

        [HttpPost("[action]")]
        public IActionResult Add(CourseGroupViewModel model)
        {
            if (!ModelState.IsValid) return NotFound();

            var group = new CourseGroup();

            group.Id = Guid.NewGuid();
            group.Name = model.CourseGroup.Name;
            group.Description = model.CourseGroup.Description;
            group.VisualOrder = model.CourseGroup.VisualOrder;

            _uow.CourseGroupRepository.Add(group);
            _uow.Commit();
            return RedirectToAction("List");
        }
    }
}

CMSys/CMSys.Web/Areas/Admin/Views/CourseGroup/List.cshtml
@model CMSys.Web.Areas.Admin.ViewModels.CourseGroupViewModel
@{
    ViewBag.Title = "Course groups";
}

<div>
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="text-primary headerdiv" style="text-transform: uppercase; font-weight: bold"></div>
                    <button class="close crossbutton" data-dismiss="modal" area-hidden="true">X</button>
                </div>
                <div class="modal-body">
                    <form class="formpopup" asp-area="Admin" asp-controller="CourseGroup">
                        <div class="form-group">
                            <input asp-for="CourseGroup.Id" class="form-control-plaintext idlabel" type="hidden" readonly="readonly" />
                        </div>
                        <div class="form-group" style="margin-top: -15px">
                            <label asp-for="CourseGroup.Name">Name</label>
                            <input asp-for="CourseGroup.Name" class="form-control namelabel" value=""/>
                            <span class="text-danger namespan"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CourseGroup.Description">Description</label>
                            <textarea asp-for="CourseGroup.Description" class="form-control owerflow-auto descriptionlabel" placeholder="Put description here" rows="5" style="height: 60px"></textarea>
                        </div>
                        <div class="form-group">
                            <label asp-for="CourseGroup.VisualOrder">Order</label>
                            <input asp-for="CourseGroup.VisualOrder" class="form-control orderlabel" />
                            <span class="text-danger orderspan"></span>
                        </div>
                        <div>
                            <input onclick="onButtonEditClick(event)" type="button" class="btn btn-primary submitinput" />
                            <a type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div id="modDialog3" class="modal fade">
        <div id="dialogContent" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="text-primary headerdiv" style="text-transform: uppercase; font-weight: bold"></div>
                    <button class="close crossbutton" data-dismiss="modal" area-hidden="true">X</button>
                </div>
                <div class="modal-body">
                    <form class="formpopup" asp-area="Admin" asp-controller="CourseGroup">
                        <div class="form-group">
                            <input asp-for="CourseGroup.Id" class="form-control-plaintext idlabel" type="hidden" readonly="readonly" />
                        </div>
                        <div class="form-group" style="margin-top: -15px">
                            <label asp-for="CourseGroup.Name">Name</label>
                            <input asp-for="CourseGroup.Name" class="form-control namelabel" value="" />
                            <span asp-validation-for="CourseGroup.Name" class="text-danger namespan"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CourseGroup.Description">Description</label>
                            <textarea asp-for="CourseGroup.Description" class="form-control owerflow-auto descriptionlabel" placeholder="Put description here" rows="5" style="height: 60px"></textarea>
                        </div>
                        <div class="form-group">
                            <label asp-for="CourseGroup.VisualOrder">Order</label>
                            <input asp-for="CourseGroup.VisualOrder" class="form-control orderlabel" />
                            <span asp-validation-for="CourseGroup.VisualOrder" class="text-danger orderspan"></span>
                        </div>
                        <div>
                            <input asp-action="Add" type="submit" class="btn btn-primary submitinput" />
                            <a type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<partial name="DeletePopUp"/>

<div style="display: flex;float: right; margin-top: -10px">
    <a onclick="onAddGroupClick(event)" class="btn btn-outline-light" style="margin-bottom: 10px; border: 1px solid lightgray; width: 37px; height: 37px; display: block; background: whitesmoke ">
        <i onclick="onAddGroupClick(event)" class="fa fa-plus" aria-hidden="true" style="font-size:25px; display: block; margin-left: -47%; color: gray"></i>
    </a>
</div>

<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Order</th>
            <th scope="col" style="width: 100px">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model.Groups)
        {
            <tr id="@group.Id">
                <th class="group_name">@group.Name</th>
                <td class="group_description">@group.Description</td>
                <td class="group_order">@group.VisualOrder</td>
                <td>
                    <a onclick="onEditGroupClick(event)" id="@group.Id" class="btn btn-outline-light" style="border: 1px solid #007bff; margin-left: 5px; width: 30px;">
                        <i class="fas" id="@group.Id" style="font-size: 20px; display: block; margin-left: -185%; color: #007bff;"> &#xf303; </i>
                    </a>
                    <a onclick="onDeleteGroupClick(event)" id="@group.Id" class="btn btn-outline-light" style="border: 1px solid red; margin-left: 5px; width: 30px;">
                        <i id="@group.Id" style="font-size: 20px; display: block; margin-left: -172%; color: red;" class="fa fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}