CMSys/CMSys.Web/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CMSys.Core.Common;
using CMSys.Core.Entities;
using CMSys.Core.Repositories;
using CMSys.Web.Areas.Admin.ViewModels;
using CMSys.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Route("admin/[controller]")]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _uow;

        public UserController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        [Route("")]
        [Route("[area]/[controller]/[action]")]
        public async Task<IActionResult> List(int page = 1, UserViewModel model = null)
        {
            var userFilter = new UserFilter(page);
            var tuple = await _uow.UserRepository.GetPageItems(userFilter, model?.Name);
            userFilter.Count = tuple.Item2;
            return View(new UserViewModel
            {
                UserFilter = userFilter,
                PageModel = PageViewModel<User>.Create(tuple.Item1, tuple.Item2, page, userFilter.Size, default,
                    default)
            });
        }

        [Route("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Details(Guid id, int page)
        {
            var user = _uow.UserRepository.Find(id);
            return user == null
                ? (IActionResult) NotFound()
                : View(new EditUserViewModel
                {
                    User = user,
                    Page = page
                });
        }

        [HttpGet("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Edit(Guid id, int page)
        {
            var user = _uow.UserRepository.Find(id);
            if (user == null)
                return NotFound();

            return View(new EditUserViewModel
            {
                Page = page,
                User = user,
                Roles = GetExtraRoles(user)
            });
        }

        [HttpPost("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Edit(EditUserViewModel model)
        {
            var user = _uow.UserRepository.Find(model.User.Id);
            if (user == null) return NotFound();
            if (!ModelState.IsValid)
            {
                model.User = user;
                return View(model);
            }

            user.PasswordSalt = Guid.NewGuid().ToString();
            user.PasswordHash = UserPasswords.ComputeHash(model.NewPassword, user.PasswordSalt);

            _uow.Commit();
            return RedirectToAction("Edit", new {id = user.Id, page = model.Page});
        }

        [HttpPost("[area]/[controller]/[action]")]
        public IActionResult AddRole(EditUserViewModel model)
        {
            var user = _uow.UserRepository.Find(model.User.Id);
            if (user == null) return NotFound();
            var role = _uow.RoleRepository.Find(model.Role);

            var userRole = new UserRole {Role = role, RoleId = role.Id, User = user, UserId = user.Id};
            _uow.UserRoleRepository.Add(userRole);

            _uow.Commit();
            return RedirectToAction("Edit", new {id = user.Id, page = model.Page});
        }

        [HttpPost("[area]/[controller]/[action]")]
        public IActionResult RemoveRole(EditUserViewModel model)
        {
            var user = _uow.UserRepository.Find(model.User.Id);
            if (user == null) return NotFound();
            var userRole = _uow.UserRoleRepository.Find(user.Id, model.Role);
            if (userRole == null) return RedirectToAction("Edit", new {id = user.Id, page = model.Page});
            _uow.UserRoleRepository.Remove(userRole);
            _uow.Commit();
            return RedirectToAction("Edit", new {id = user.Id, page = model.Page});
        }

        public IEnumerable<Role> GetExtraRoles(User user)
        {
            var roles = new List<Role>();
            roles.AddRange(_uow.RoleRepository.List());
            var count = user.UserRole.Count();
            for (var i = 0; i < count; i++) roles.Remove(user.UserRole.ElementAt(i).Role);

            return roles;
        }
    }
}

CMSys/CMSys.Web/Controllers/CourseController.cs
using System;
using System.Threading.Tasks;
using CMSys.Core.Common;
using CMSys.Core.Entities;
using CMSys.Core.Repositories;
using CMSys.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    [Route("user/[controller]")]
    public class CourseController : Controller
    {
        private readonly IUnitOfWork _uow;

        public CourseController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        [Route("")]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> List(int page = 1, Guid groupId = default, Guid typeId = default)
        {
            var courseFilter = new CourseFilter(groupId, typeId, page);
            var tuple = await _uow.CourseRepository.GetPageItems(courseFilter);
            return View(new CourseViewModel
            {
                PageModel = PageViewModel<Course>.Create(tuple.Item1, tuple.Item2, page, courseFilter.Size, groupId, typeId),
                Groups = _uow.CourseGroupRepository.List(),
                Types = _uow.CourseTypeRepository.List(),
                CurrentType = typeId,
                CurrentGroup = groupId
            });
        }

        [Route("[controller]/[action]/{id:guid}")]
        public IActionResult Details(Guid id)
        {
            var course = _uow.CourseRepository.Find(id);
            return course == null ? (IActionResult) NotFound() : View(course);
        }
    }
}

CMSys/CMSys.Web/Controllers/TrainerController.cs
using CMSys.Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    [Route("user/[controller]")]
    public class TrainerController : Controller
    {
        private readonly IUnitOfWork _uow;

        public TrainerController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        [Route("")]
        [Route("[controller]/[action]")]
        public IActionResult List(int page = 1)
        {
            return View(_uow.TrainerRepository.Groups());
        }
    }
}

CMSys/CMSys.Web/Controllers/UserDetailsController.cs
using System;
using CMSys.Core.Common;
using CMSys.Core.Repositories;
using CMSys.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    [Route("user/[controller]")]
    public class UserDetailsController : Controller
    {
        private readonly IUnitOfWork _uow;

        public UserDetailsController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        [Route("[action]")]
        public IActionResult Details(string email)
        {
            var user = _uow.UserRepository.FindByEmail(email);
            return user == null ? (IActionResult)NotFound() : View(user);
        }

        [HttpGet("[action]/{id:guid}")]
        public IActionResult ChangePassword(Guid id)
        {
            var user = _uow.UserRepository.Find(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(new ChangePasswordViewModel
            {
                Id = user.Id
            });
        }

        [HttpPost("[action]/{id:guid}")]
        public IActionResult ChangePassword(ChangePasswordViewModel model)
        {
            var user = _uow.UserRepository.Find(model.Id);
            if (user == null) return NotFound();
            if (!ModelState.IsValid)
            {
                model.Id = user.Id;
                return View(model);
            }

            user.PasswordSalt = Guid.NewGuid().ToString();
            user.PasswordHash = UserPasswords.ComputeHash(model.NewPassword, user.PasswordSalt);

            _uow.Commit();
            return RedirectToAction("Index","Home");
        }
    }
}

CMSys/CMSys.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainer" asp-action="List">Trainers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="List">Courses</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Trainer" asp-action="List">Trainers(Admin)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Course" asp-action="List">Courses(Admin)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="CourseGroup" asp-action="List">Course Groups(Admin)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="TrainerGroup" asp-action="List">Trainer Groups(Admin)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="List">Users(Admin)</a>
                            </li>
                    </ul>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row ml-auto ">
                    <div class="row">
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link text-primary" asp-controller="UserDetails" asp-action="Details" asp-route-email="@Context.User.Claims.ElementAt(1).Value">@(Context.User.Identity.Name)</a>
                            <a class="nav-link text-primary" asp-controller="Login" asp-action="Logout">Sign out</a>
                        }
                        else
                        {
                            <a class="nav-link text-primary" asp-controller="Login" asp-action="Login">Sign in</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <div class="card" style="margin-top: 20px;">
                <h5 class="card-header">
                    @ViewBag.Title
                </h5>
                <div class="card-body" style="padding-left: unset; padding-right: unset;">
                    <div class="container">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <script src="~/js/common.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", false)
</body>
</html>